-- IFNULL(NULL아닐 때, NULL일 때)
-- WHERE 절에는 IF 조건 사용 불가능
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO,'NONE') AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD='W'
ORDER BY AGE DESC, PT_NAME ASC

--IFNULL 다시 한 번..
SELECT ROUND(AVG(IFNULL(LENGTH,10)),2) AS AVERAGE_LENGTH
FROM FISH_INFO 

-- CONCAT(붙일 값1, 붙일 값2)
SELECT CONCAT(MAX(LENGTH),'cm') AS MAX_LENGTH
FROM FISH_INFO

-- DATEDIFF(큰 날짜, 작은 날짜) cf) 작은 날짜, 큰 날짜는 음수값 반환
-- 실제 대여 일수를 계산하기 위해서는 +1을 해줘야함
SELECT HISTORY_ID, CAR_ID, 
    DATE_FORMAT(START_DATE, '%Y-%m-%d') AS START_DATE, 
    DATE_FORMAT(END_DATE, '%Y-%m-%d') AS END_DATE,
    IF ( DATEDIFF(END_DATE,START_DATE)+1 >= 30,'장기 대여','단기 대여') AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE LIKE '2022-09%'
ORDER BY HISTORY_ID DESC

