-- IFNULL(NULL아닐 때, NULL일 때)
-- WHERE 절에는 IF 조건 사용 불가능
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO,'NONE') AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD='W'
ORDER BY AGE DESC, PT_NAME ASC

-- CONCAT(붙일 값1, 붙일 값2)
SELECT CONCAT(MAX(LENGTH),'cm') AS MAX_LENGTH
FROM FISH_INFO
