SELECT 
    CAR_TYPE, COUNT(OPTIONS) AS CARS
    
FROM ( 
    SELECT CAR_TYPE, 
    IF(OPTIONS LIKE '%통풍시트%' OR 
       OPTIONS LIKE '%열선시트%' OR 
       OPTIONS LIKE '%가죽시트%', OPTIONS, NULL) AS OPTIONS
    FROM CAR_RENTAL_COMPANY_CAR
    ) AS FILTERED
GROUP BY CAR_TYPE
ORDER BY CAR_TYPE