# .github/workflows/auto-classify-notion.yml 의 steps에 아래를 Run classifier script 전에 넣으세요
- name: Debug: show event path and event (first 2000 chars)
  run: |
    echo "GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH"
    echo "Listing event file:"
    if [ -f "$GITHUB_EVENT_PATH" ]; then
      echo "=== event.json (first 2000 chars) ==="
      head -c 2000 "$GITHUB_EVENT_PATH" || true
      echo
    else
      echo "No event file at $GITHUB_EVENT_PATH"
    fi

- name: Debug: show changed files from event (quick parse)
  run: |
    if [ -f "$GITHUB_EVENT_PATH" ]; then
      python - <<'PY'
import json,os
p=os.environ.get("GITHUB_EVENT_PATH")
with open(p,encoding="utf-8") as f:
    e=json.load(f)
commits=e.get("commits",[])
print("num_commits:", len(commits))
files=[]
for c in commits:
    files+=c.get("added",[])+c.get("modified",[])+c.get("removed",[])
print("changed files sample (first 50):", files[:50])
PY
    else
      echo "No event file to parse"
    fi
